/// Flutter icons AltaIconMovie
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AltaIconMovie
///      fonts:
///       - asset: fonts/AltaIconMovie.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AltaIconMovie {
  AltaIconMovie._();

  static const _kFontFam = 'AltaIconMovie';
  static const String? _kFontPkg = null;

  // ignore: lowerCamelCase identifier
  static const IconData icon_movie = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
